apps/crud/models.py
# 기업 연계 프로젝트 1

from datetime import datetime

# flask-login 내에 UserMixin 을 import
from flask_login import UserMixin, current_user  # type: ignore

# password_hash 처리를 위한 모듈 import, check_password_hash 추가
from werkzeug.security import check_password_hash, generate_password_hash

# apps.app 모듈에서 db import, 추가 import login_manager
from apps import db, login_manager


# db.model을 상속한 User 클래스 상속, 더하여 UserMixin 상속
class User(db.Model, UserMixin):
    # 테이블명을 지정한다.
    __tablename__ = "users"
    # 컬럼 정의
    id = db.Column(db.Integer, primary_key=True)  # primary_key 속성 부여
    username = db.Column(db.String(100), index=True)  # index 색인
    user_id = db.Column(db.String(100), nullable=False, unique=True)
    email = db.Column(db.String(255), index=True, unique=True)  # unique, index 설정
    password_hash = db.Column(db.String(255))
    is_kakao = db.Column(db.Boolean, default=False)
    kakao_access_token = db.Column(db.String(255), nullable=True)
    created_at = db.Column(
        db.DateTime, default=datetime.now
    )  # default는 기본값(현재시간)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    # onupdate는 데이터를 수정할때마다 시간이 업데이트될 수 있게

    # backref를 이용하여 릴레이션 정보를 설정한다.
    # user_images = db.relationship("UserImage", backref="user", order_by="desc(UserImage.id)")

    # 비밀번호를 설정하기 위한 프로퍼티
    @property
    def password(self):
        raise AttributeError("읽어 들일 수 없음")  # raise 예외발생시키는 것

    # 비밀번호 설정하기 위해 setter 함수로 해시화한 비밀번호를 설정한다.
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 비밀번호 체크(패스워드 확인)
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # # 이메일 주소 중복 체크
    # def is_duplicate_email(self):
    #     return User.query.filter_by(email=self.email).first()
    def is_duplicate_user_id(self):
        return User.query.filter_by(user_id=self.user_id).first()

    # 로그인하고 있는 사용자 정보를 얻는 함수를 작성
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

apps/crud/forms.py
# 기업 연계 프로젝트 1

from flask_wtf import FlaskForm  # type: ignore
from wtforms import PasswordField, StringField, SubmitField  # type: ignore
from wtforms.validators import DataRequired, Email, Length  # type: ignore


# 사용자 신규 작성과 사용자 편집 폼 클래스
class UserForm(FlaskForm):
    # 사용자 폼의 username 속성의 라벨과 검증 설정
    username = StringField(
        "사용자명",
        validators=[
            DataRequired(message="사용자명은 필수입니다."),
            Length(min=2, max=30, message="최소 2글자부터 30문자 이내로 입력하세요"),
        ],
    )

    # user_id 속성의 레이블과 검증 설정
    user_id = StringField(
        name="아이디",
        validators=[
            DataRequired(message="아이디는 필수 입니다."),
            Length(min=4, max=15, message="최소 2글자부터 20문자 이내로 입력하세요"),
        ],
    )

    # # email 속성의 레이블과 검증 설정
    # email = StringField(
    #     "메일 주소",
    #     validators=[
    #         DataRequired(message="메일 주소는 필수입니다."),
    #         Email(message="메일 주소의 형식으로 입력해 주세요."),
    #     ],
    # )

    # 사용자 폼의 password 속성의 레이블과 검증 설정
    password = PasswordField(
        "비밀번호",
        validators=[DataRequired(message="비밀번호는 필수 입니다.")],
    )

    # 사용자 폼의 submit의 문자를 설정
    submit = SubmitField("신규 등록")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
# 기업 연계 프로젝트 1

# db를 import
from flask import Blueprint, redirect, render_template, url_for

from apps import db

# 만들둔 Form 클래스를 import
from apps.crud.forms import UserForm

# User  클래스를 import
from apps.crud.models import User

# login_required을 import
from flask_login import login_required  # type: ignore

# Blueprint로 crud 앱을 생성한다.
crud = Blueprint(
    "crud",
    __name__,
    static_folder="static",
    template_folder="templates",
)


# 맵핑 정보 생성
@crud.route("/")
def index():
    return render_template("crud/index.html")


# 사용자 신규 등록을 위한 엔드포인트 작성
@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    # UserForm 클래스를 인스턴스화
    form = UserForm()
    if form.validate_on_submit():  # submit 클릭시 검증에 문제가 없는 경우.
        # 사용자 정보 생성
        user = User(
            user_id=form.user_id.data,
            username=form.username.data,
            # email=form.email.data,
            password=form.password.data,
        )

        # DB작업으로 사용자를 추가하고 커밋
        db.session.add(user)
        db.session.commit()

        # 사용자 일람 화면으로 리다이렉트
        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


@crud.route("/users")
@login_required
def users():
    """사용자 일람을 얻는 함수"""
    # users = db.session,query(User).all() 이 코드나 아래 코드를 쓰면된다. 리턴은 동일하게쓴다.``
    users = User.query.all()
    return render_template("/crud/index.html", users=users)


# 사용자 편집을 위한 엔드포인트 작업
@crud.route("/users/<user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    form = UserForm()

    # User 모델을 이용하여 사용자를 취득
    user = User.query.filter_by(id=user_id).first()

    # form으로부터 제출된 경우는 사용자를 갱신하여 사용자의 일람 화면으로 리다이렉트
    if form.validate_on_submit():  # post 메서드로 수정 정보가 들어온 경우
        user.username = form.username.data
        # user.email = form.email.data
        user.password = form.password.data
        # DB에 적용
        db.session.add(user)  # primary key의 값이 있는 경우는 수정, 없으면 생성이다
        db.session.commit()

        return redirect(url_for("crud.users"))  # 수정완료. 일람으로 이동
    # GET으로 접근한 경우 HTML을 반환
    return render_template("crud/edit.html", user=user, form=form)


@crud.route("/users/<user_id>/delete", methods=["post"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8" />
    <!-- title을 상속처에서 구현한다.-->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('crud.static', filename='style.css') }}"/>
  </head>
  <body>
    <div>
      {% if current_user.is_authenticated %}
      <p>
        <spen>{{ current_user.username }}</span>
        <spen><a href= "{{ url_for ('auth.logout') }}">로그아웃</a></span>
      </p>
      {% endif %}
    </div>
    <!-- content를 상속처에서 구현한다 -->
    {% block content %}{% endblock %}
  </body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %} {% block title %}사용자의 신규 작성{% endblock %}
{% block content%}
<h2>사용자 신규 작성</h2>
<form
  action="{{ url_for('crud.create_user') }}"
  method="POST"
  novalidate="novalidate"
  >
  {{ form.csrf_token }}
  
  <p>{{ form.user_id.label }} {{ form.user_id(placeholder="아이디") }}</p>
  {% for error in form.user_id.errors %}
  <span style="color: red">{{ error }}</span>
  {% endfor %}
  
  <p>{{ form.username.label }} {{ form.username(placeholder="사용자명") }}</p>
  {% for error in form.username.errors %}
  <span style="color: red">{{ error }}</span>
  {% endfor %}


  <p>{{ form.password.label }} {{ form.password(placeholder="비밀번호") }}</p>
  {% for error in form.password.errors %}
  <span style="color: red">{{ error }}</span>
  {% endfor %}

  <p>{{ form.submit() }}</p>

</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %} {% block title %}사용자의 편집{% endblock %} {%
block content%}
<h2>사용자의 편집</h2>
<form
  action="{{ url_for('crud.edit_user', user_id=user.id) }}"
  method="POST"
  novalidate="novalidate"
>
  {{ form.csrf_token }}
  <p>
    {{ form.username.label }} {{ form.username(placeholder="사용자명",
    value=user.username) }}
  </p>
  {% for error in form.username.errors %}
  <span style="color: red">{{ error }}</span>
  {% endfor %}

  <p>{{ form.password.label }} {{ form.password(placeholder = "비밀번호") }}</p>
  {% for error in form.password.errors %}
  <span style="color: red">{{ error }}</span>
  {% endfor %}

  <p>{{ form.submit(value='업데이트') }}</p>
</form>
<form action = "{{ url_for ('crud.delete_user', user_id=user.id) }}" method="post">
  {{ form.csrf_token }}
  <input type="submit" value="삭제" />
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %} {% block title %} 사용자의 일람 {% endblock %} {%
block content %}
<h2>사용자 일람</h2>

<a href="{{ url_for('crud.create_user')}}">사용자 신규 작성</a>

<table>
  <tr>
    <th>사용자 번호</th>
    <th>사용자 ID</th>
    <th>사용자 이름</th>
  </tr>
  {% for user in users %}
  <tr>
    <td>
      <a href="{{ url_for('crud.edit_user', user_id=user.id)}}">
        {{ user.id }}
      </a>
    </td>
    <td>{{ user.user_id }}</td>
    <td>{{ user.username }}</td>
  </tr>
  {% endfor%}
</table>
{% endblock %}