apps/cam/views.py
# 기업 연계 프로젝트 1

from flask import (
    Blueprint,
    redirect,
    render_template,
    url_for,
    jsonify,
    request,
    flash,
    current_app,
    send_from_directory,
    abort,
)
from flask_wtf.csrf import generate_csrf
from apps import db
from apps.app import (
    db,
    camera_streams,
    record_camera_with_context,
    stop_recording,
    stop_recording_all,
    start_recording_all,
)
from apps.cam.models import Cams, Videos
from apps.cam.forms import CameraForm, DeleteCameraForm, VideoSearchForm, ShutdownForm
from flask_login import login_required  # type: ignore
from pathlib import Path
from datetime import datetime, date, time

from collections import defaultdict
import os
from threading import Thread
import boto3

# from threading import Event

from S3upload.s3client import delete_file, generate_presigned_url
from S3upload.s3_config import BUCKET

# 압축 다운로드 기능을 위한 라이브러리
import tempfile
import zipfile
from werkzeug.utils import secure_filename
from flask import send_file

# 페이징처리를 위한 import
from flask_paginate import Pagination, get_page_parameter

# 소켓통신을 위해
import socket
import json
import cv2 as cv


# Blueprint로 crud 앱을 생성한다.
cam = Blueprint(
    "cam",
    __name__,
    static_folder="static",
    template_folder="templates",
)


RECOGNITION_MODULE_HOST = "localhost"
RECOGNITION_MODULE_PORT = 8001
RECOGNITION_MODULE_STATUS_PORT = 8002  # 상태 확인용 새 포트

recognition_module_running = False


@cam.route("/check_status")
def check_status():
    global recognition_module_running
    data = None
    try:
        with socket.create_connection(
            (RECOGNITION_MODULE_HOST, RECOGNITION_MODULE_STATUS_PORT), timeout=1
        ) as sock:
            recognition_module_running = True
            current_app.logger.info("인식 모듈 연결됨 (상태 확인)")
            data = sock.recv(2048).decode("utf-8")
            data = json.loads(data)

    except (ConnectionRefusedError, TimeoutError):
        recognition_module_running = False
        current_app.logger.warning("인식 모듈 연결 끊김 또는 응답 없음 (상태 확인)")
    except:
        recognition_module_running = False
        pass

    cam_list = {}

    for i in Cams.query.all():
        cam_list[i.id] = i.cam_name

    return {
        "running": recognition_module_running,
        "cam_data": data,
        "cam_list": cam_list,
    }


@cam.route("/check_cam_status")
def check_cam_status():
    num_total_cams = Cams.query.count()
    check_active()
    num_active_cams = Cams.query.filter_by(is_active=True).count()
    num_recording_cams = Cams.query.filter_by(is_recording=True).count()
    num_dt_cams = 0
    try:
        with socket.create_connection(
            (RECOGNITION_MODULE_HOST, RECOGNITION_MODULE_STATUS_PORT), timeout=1
        ) as sock:
            data = sock.recv(2048).decode("utf-8")
            data = json.loads(data)
            for v in data:
                if data[v] == True:
                    num_dt_cams += 1

    except (ConnectionRefusedError, TimeoutError):
        current_app.logger.warning("인식 모듈 연결 끊김 또는 응답 없음 (상태 확인)")
    except:
        pass

    return {
        "total_cams": num_total_cams,
        "active_cams": num_active_cams,
        "rec_cams": num_recording_cams,
        "dt_cams": num_dt_cams,
    }


@cam.route("/check_active")
def check_active():
    cams = Cams.query.all()
    cams_status = {}
    try:
        cap = None
        for cam in cams:
            cap = cv.VideoCapture(cam.cam_url)
            if cap.isOpened():
                cam.is_active = True
                # current_app.logger.info(f"카메라 {cam.cam_name}가 활성화되었습니다.")

            elif not cap.isOpened() and cam.is_active:
                cam.is_active = False
                # current_app.logger.info(f"카메라 {cam.cam_name}가 비활성화되었습니다.")
            cams_status[cam.id] = cam.is_active

    except Exception as e:
        current_app.logger.error(f"카메라 동작 확인 중 오류 발생: {e}")
        db.session.rollback()
    finally:
        if cap is not None:
            cap.release()
        db.session.commit()

    return {"cams_status": cams_status}


@cam.route("/shutdown", methods=["POST"])
def shutdown_module():
    global recognition_module_running
    form = ShutdownForm()
    if form.validate_on_submit():
        if not check_status()["running"]:
            current_app.logger.warning(
                "인식 모듈이 실행 중이 아닙니다. 종료 신호 전송을 건너뜁니다."
            )
            return "인식 모듈이 실행 중이 아닙니다.", 200

        try:
            client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            client_socket.settimeout(5)
            client_socket.connect((RECOGNITION_MODULE_HOST, RECOGNITION_MODULE_PORT))
            client_socket.sendall(b"shutdown")
            client_socket.close()
            current_app.logger.info("인식 모듈 종료 신호 전송 성공")
            recognition_module_running = False
            return "인식 모듈에 종료 신호를 보냈습니다.", 200
        except Exception as e:
            current_app.logger.error(f"인식 모듈 종료 신호 전송 중 오류 발생: {e}")
            return f"오류: {e}", 500
    return redirect(url_for("cam.index"))


@cam.route("/", methods=["GET", "POST"])
@login_required
def index():
    form = ShutdownForm()
    data = check_status()
    return render_template(
        "cam/index.html",
        recognition_running=data["running"],
        form=form,
        cam_data=data["cam_data"],
        cam_list=data["cam_list"],
    )


# 새로운 데이터 추가 (AJAX)
@cam.route("/add", methods=["GET", "POST"])
@login_required
def add_camera():
    form = CameraForm()
    if form.validate_on_submit():
        cam = Cams(cam_name=form.cam_name.data, cam_url=form.cam_url.data)
        if cam.is_duplicate_url():
            flash("지정 영상 주소는 이미 등록되어 있습니다.")
            return redirect(url_for("cam.add_camera"))
        db.session.add(cam)
        db.session.commit()
        next_ = request.args.get("next")
        # next가 비어 있거나, "/"로 시작하지 않는 경우 -> 상대경로 접근X.
        if next_ is None or not next_.startswith("/"):
            # next의 값을 엔드포인트 cam.cameras로 지정
            next_ = url_for("cam.cameras")
        # redirect
        return redirect(next_)
    return render_template("cam/addCamera.html", form=form)


@cam.route("/<camera_id>/edit", methods=["GET", "POST"])
@login_required
def edit_camera(camera_id):
    form = CameraForm()
    cam = Cams.query.filter_by(id=camera_id).first()

    # form 으로 부터 제출된경우는 사용자를 갱신하여 사용자의 일람 화면으로 리다이렉트
    if form.validate_on_submit():
        cam.cam_name = form.cam_name.data
        cam.cam_url = form.cam_url.data
        db.session.add(cam)
        db.session.commit()
        return redirect(url_for("cam.cameras"))

    # GET의 경우에는 HTML 반환
    return render_template("cam/editCamera.html", cam=cam, form=form)


@cam.route("/<camera_id>/delete", methods=["POST"])
@login_required
def delete_camera(camera_id):
    cam = Cams.query.filter_by(id=camera_id).first()
    db.session.delete(cam)
    db.session.commit()
    return redirect(url_for("cam.cameras"))


@cam.route("/cameras")
@login_required
def cameras():
    cams = Cams.query.all()
    csrf_token = generate_csrf()
    form = DeleteCameraForm()  # Instantiate the form
    return render_template(
        "cam/cameraDB.html", cams=cams, csrf_token=csrf_token, form=form
    )


@cam.route("/live")
def live():
    from apps.app import camera_streams  # 순환 참조 방지

    cams = Cams.query.all()
    return render_template("cam/live.html", cams=cams)


@cam.route("/status")
def cam_status():
    from apps.app import camera_streams  # 순환 참조 방지

    cams = Cams.query.all()
    return render_template("cam/cam_status.html", cams=cams)


@cam.route("/start_record/<int:camera_id>")
@login_required
def start_record(camera_id):
    cam_info = Cams.query.get(camera_id)
    if cam_info:
        app = current_app._get_current_object()
        if not cam_info.is_recording:  # 이미 녹화 중이 아닌 경우에만 시작
            recording_thread = Thread(
                target=record_camera_with_context,
                args=(app, cam_info.cam_url, cam_info.id),
                daemon=True,
            )
            recording_thread.start()
            cam_info.is_recording = True
            camera_streams[cam_info.id] = recording_thread
            # print(f"camera_streams (start): {camera_streams}")
            db.session.commit()
            current_app.logger.info(f"카메라 '{cam_info.cam_name}' 녹화 시작 요청됨.")
        else:
            current_app.logger.warning(
                f"카메라 '{cam_info.cam_name}'은 이미 녹화 중입니다."
            )
    return redirect(url_for("cam.cam_status"))


@cam.route("/stop_record/<int:camera_id>")
@login_required
def stop_record_route(camera_id):
    stop_recording(camera_id)
    return redirect(url_for("cam.cam_status"))


@cam.route("/stop_all_records")
@login_required
def stop_all_records_route():
    print(f"camera_streams (stop all): {camera_streams}")
    stop_recording_all()
    return redirect(url_for("cam.cam_status"))


@cam.route("/start_all_records")
@login_required
def start_all_records_route():
    start_recording_all()
    print(f"camera_streams (start all): {camera_streams}")
    return redirect(url_for("cam.cam_status"))


@cam.route("/video/<path:filename>")
@login_required
def serve_video(filename):
    return send_from_directory(current_app.config["VIDEO_FOLDER"], filename)


@cam.route("/dt_video/<path:filename>")
@login_required
def serve_dt_video(filename):
    return send_from_directory(current_app.config["DT_VIDEO_FOLDER"], filename)


@cam.route("/play_video/<int:video_id>")
@login_required
def play_video(video_id):
    video = Videos.query.get_or_404(video_id)
    current_app.logger.info(
        f"Attempting to play video with id: {video_id}, path: {video.video_path}"
    )

    if video.is_dt:
        recorded_video_base_dir = Path(current_app.config["DT_VIDEO_FOLDER"])
    else:
        recorded_video_base_dir = Path(current_app.config["VIDEO_FOLDER"])

    current_app.logger.info(f"recorded_video_base_dir: {recorded_video_base_dir}")

    path_obj = Path(video.video_path)

apps/cam/templates/cam/cam_status.html
{% extends "cam/base.html" %} 
{%block title%}카메라 관리{% endblock %} 

{% block content %}
  <div class="cover-container w-100 h-100 p-3 m-auto">

    {% include "cam/header.html" %}

    <main>
      <div class= "table-responsive">
        <h2>카메라 상태</h2>
        <table class = "table table-striped table-hover align-middle">
          <thead>
            <tr>
              <th>이름</th>
              <th>URL</th>
              <th>카메라 동작 상태</th>
              <th>녹화 상태</th>
              <th>액션</th>
            </tr>
          </thead>
          <tbody>
            {% for cam in cams %}
            <tr>
              <td class="td">{{ cam.cam_name }}</td>
              <td class="td text-break">{{ cam.cam_url }}</td>
              <td class="td" id = "cams_status_{{ cam.id }}">
                {% if cam.is_active %} 활성화 {% else %} 비활성화 {% endif %}
              </td>
              <td class="td">
                {% if cam.is_recording %} 녹화 중 {% else %} 녹화 대기 중 {%
                endif %}
              </td>
              <td class="td">
                {% if not cam.is_recording %}
                <button class = "btn btn-sm btn-dark bg-success fw-bold">
                <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" 
                href="{{ url_for('cam.start_record', camera_id=cam.id) }}">녹화 시작</a>
                </button>
                {% else %}
                <button class = "btn btn-sm btn-dark bg-danger fw-bold">
                <a class="link-dark link-offset-2 link-underline link-underline-opacity-0"
                href="{{ url_for('cam.stop_record_route', camera_id=cam.id) }}">녹화 중지</a>
                </button>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        
        <div>
          <button class = "btn btn-sm btn-dark bg-success fw-bold">
            <a class="link-light link-offset-2 link-underline link-underline-opacity-0" href="{{ url_for('cam.start_all_records_route')}}" alt="모든 녹화 시작 버튼">모든 녹화 시작</a>
          </button>
          <button class = "btn btn-sm btn-dark bg-danger fw-bold">
            <a class="link-light link-offset-2 link-underline link-underline-opacity-0" href="{{ url_for('cam.stop_all_records_route') }}" alt="모든 녹화 중지 버튼">모든 녹화 중지</a>
          </button>
          <button class = "btn btn-sm btn-dark bg-white fw-bold">
            <a class="link-dark link-offset-2 link-underline link-underline-opacity-0" href="{{ url_for('cam.live') }}" alt="라이브 화면 버튼">라이브 화면</a>
          </button>
        </div>
      </main>
      {% include "cam/footer.html" %} 
    </div>
  </div>
{% endblock %}
{% block scripts %}
<script>
function checkActive() {

  $.get("{{ url_for('cam.check_active')}}", function (data) {
    for (var key in data.cams_status) {
      if (data.cams_status[key]) {
        $("#cams_status_" + key).text("작동 중");
      }
      else {
          $("#cams_status_" + key).text("비활성화");
       }
    }
  });
}

setInterval(checkActive, 5000);
</script>
{% endblock %}

apps/cam/templates/cam/cameraDB.html
{% extends "cam/base.html" %}
{% block title %} 카메라 관리 데이터베이스 {%endblock %}

{% block content %}
<div class="cover-container w-100 h-100 p-3 m-auto">

	{% include "cam/header.html"%}
	<main>
		<div class="table-responsive">
			<h2>카메라 목록</h2>
			<table class="table table-striped table-hover align-middle fw-bold">
				<thead>
					<tr>
						<th>ID</th>
						<th>이름</th>
						<th>URL</th>
						<th>작업</th>
					</tr>
				</thead>
				<tbody>
					{% for cam in cams %}
					<tr>
						<td >{{ cam.id }}</td>
						<td >{{ cam.cam_name }}</td>
						<td class = "text-break">{{ cam.cam_url }}</td>
						<td>
							<a
								class="btn btn-info btn-sm"
								href="{{url_for('cam.edit_camera', camera_id=cam.id)}}"
								>수정</a
							>
							<button
								class="btn btn-danger btn-sm"
								onclick="deleteCamera('{{ cam.id }}', '{{ csrf_token }}')"
							>
								삭제
							</button>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			<a href="{{ url_for('cam.add_camera') }}" class="btn btn-primary btn-md"
				>카메라 추가</a
			>
		</div>
	</main>
		{% include "cam/footer.html" %}
</div>
{% endblock %}

{% block scripts %}
	<script>
		function deleteCamera(cameraId, csrfToken) {
			if (confirm("정말로 삭제하시겠습니까?")) {
				const form = document.createElement("form");
				form.method = "POST";
				form.action = `/cameras/${cameraId}/delete`;

				const csrfInput = document.createElement("input");
				csrfInput.type = "hidden";
				csrfInput.name = "csrf_token";
				csrfInput.value = csrfToken;

				form.appendChild(csrfInput);
				document.body.appendChild(form);
				form.submit();
			}
		}
	</script>
{% endblock %}

apps/cam/templates/cam/editCamera.html
{% extends "cam/base.html" %} {% block title %} 카메라 정보 편집{% endblock
title %} {% block content%}

<div class="cover-container p-3 m-auto">
  {% include "cam/header.html"%}
  <div class="my-auto">
    <div class="card">
      <h1 class="h3 mb-3 mt-3 fw-normal">Edit Camera</h1>
      <form
        action="{{ url_for('cam.edit_camera', camera_id=cam.id) }}"
        method="POST"
        novalidate="novalidate"
        class="form-camadd"
      >
        {{ form.csrf_token }}

        <div class="form-floating mb-3">
          {{ form.cam_name(class = "form-control dt-auth-input",
          id="floatingInput" , placeholder="Camera Name", value=cam.cam_name) }}
          <label for="floatingInput">Camera Name</label>
        </div>

        {% for error in form.cam_name.errors %}
        <span style="color: red">{{ error }} </span>
        {% endfor %}

        <div class="form-floating mb-3">
          {{ form.cam_url(class = "form-control dt-auth-input",
          id="floatingInput" ,placeholder="Video server address",
          value=cam.cam_url) }}
          <label for="floatingInput">Video server address</label>
        </div>

        <div class="form-floating mb-3">
          {% for error in form.cam_url.errors %}
          <span style="color: red">{{ error }} </span>
          {% endfor %}
          <p>
            {{ form.submit(class = "btn btn-md btn-primary btn-block
            dt-auth-btn" , value='갱신') }}
          </p>
        </div>
      </form>

      <!-- <form
      action="{{ url_for('cam.delete_camera', camera_id=cam.id) }}"
      method="POST">
      {{ form.csrf_token }}
      <input type="submit" value="삭제" />
    </form> -->
    </div>
  </div>
  {% include "cam/footer.html" %} {% endblock %}
</div>

apps/cam/templates/cam/footer.html
<footer class="footer m-auto fixed-bottom custom-footer" >
  <div class ="container-fluid"> 
    <div class ="cover-container m-auto">
      <div class="col-md-12 d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" width="20" height="20">
          <path id='footer_camera_icon' fill="#e5e7eb" d="M0 128C0 92.7 28.7 64 64 64l256 0c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 448c-35.3 0-64-28.7-64-64L0 128zM559.1 99.8c10.4 5.6 16.9 16.4 16.9 28.2l0 256c0 11.8-6.5 22.6-16.9 28.2s-23 5-32.9-1.6l-96-64L416 337.1l0-17.1 0-128 0-17.1 14.2-9.5 96-64c9.8-6.5 22.4-7.2 32.9-1.6z"/></svg> <path d="M0 128C0 92.7 28.7 64 64 64l256 0c35.3 0 64 28.7 64 64l0 256c0 35.3-28.7 64-64 64L64 448c-35.3 0-64-28.7-64-64L0 128zM559.1 99.8c10.4 5.6 16.9 16.4 16.9 28.2l0 256c0 11.8-6.5 22.6-16.9 28.2s-23 5-32.9-1.6l-96-64L416 337.1l0-17.1 0-128 0-17.1 14.2-9.5 96-64c9.8-6.5 22.4-7.2 32.9-1.6z"/>
        </svg>
        <span class="fw-bold fs-6 mx-1">Camera</span>  
      </div>
      <div class = "col-md-12 hstack gap-1">
        <div><strong  id="total_cam_cnt">전체 카메라 {{ num_total_cams }}</strong></div>
        <div class = "vr mx-1"></div>
        <div><strong class ="text-info" id="act_cam_cnt">동작 중 {{ num_active_cams }}</strong></div>

        <div class = "vr mx-1"></div>
        <div><strong class ="text-success" id="rec_cam_cnt"> 녹화 중 {{ num_recording_cams }}</strong></div>

        <div class = "vr mx-1"></div>
        <div><strong class ="text-info" id="dt_cam_cnt"> 인식 모듈 확인중...</strong></div>

        <a class = "ms-auto mb-2 px-2 link-offset-2 link-underline link-underline-opacity-0 fw-bold" href ="#">Top</a>

      </div>
    </div>
  </div>
</footer>

{% block scripts %}

<script>
  function checkCamStatus() {
    $.get("{{ url_for('cam.check_cam_status') }}", function (data) {
      console.log(data)
      document.getElementById('total_cam_cnt').innerHTML = "전체 카메라 " + data['total_cams'];
      document.getElementById('act_cam_cnt').innerHTML = "동작 중 " + data['active_cams'];
      document.getElementById('rec_cam_cnt').innerHTML = "녹화 중 " + data['rec_cams'];
      document.getElementById('dt_cam_cnt').innerHTML = "인식 모듈 " + data['dt_cams'];
    });
  }

  // 5초마다 상태 체크
  setInterval(checkCamStatus, 5000);

</script>
{% endblock %}

apps/cam/templates/cam/index.html
{% extends "cam/base.html" %} {% block title %} Home {% endblock %} {% block
content %}
<div class="cover-container w-100 h-100 p-3 mx-auto">
  {% include "cam/header.html" %}
  <main class="m-auto px-5">
    <h1>스마트 CCTV 관리</h1>
    <p class="lead">
      이 페이지는 실시간 물체 감지 기능을 갖춘 CCTV 관리 시스템입니다. 간편한
      설정으로 보안 환경을 강화하고, 감지된 영상을 효율적으로 관리하세요.
    </p>

    <h2>인식 모듈 상태</h2>
    <p
      id="status-text"
      class="lead {% if recognition_running %}text-success{% else %}text-danger{% endif %}">
      {% if recognition_running %} 실행 중 {% else %} 중지됨 {% endif %}
    </p>
    <div class="row row-cols-1 row-cols-md-4 g-4 mt-3">
      {% if recognition_running %}
        {% for key, cam in cam_data.items() %}
          <div class="col">
            <div class="card" style="border: none;">
              <div class="card-body">
                <h5>
                  <i class="bi bi-camera-video-fill me-2"></i>{{ cam ['cam_name'] }}
                  <span class="badge {% if cam['dt_active'] %}bg-success{% else %}bg-secondary{% endif %}">
                    {% if cam['dt_active'] %}작동 중{% else %}작동 불가{% endif %}
                  </span>
                </h5>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <form
      id="shutdown-form"
      method="POST"
      action="{{ url_for('cam.shutdown_module') }}">
      {{ form.csrf_token }} {{ form.submit(class="btn btn-danger mt-3", disabled=not
      recognition_running) }} {##}
    </form>
  </main>
</div>
{% endblock %} {% include "cam/footer.html" %}{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

<script>

  function checkCurrentStatus() {
    $.get("{{ url_for('cam.check_status') }}", function (data) {
      const statusText = $("#status-text");
      const submitBtn = $("#shutdown-form button[type='submit']");
      if (data.running) {
        statusText
          .text("실행 중")
          .removeClass("text-danger")
          .addClass("text-success");
        submitBtn.prop("disabled", false);
      } else {
        statusText
          .text("중지됨")
          .removeClass("text-success")
          .addClass("text-danger");
        submitBtn.prop("disabled", true);
      }
    });
  }

  // 5초마다 상태 체크
  setInterval(checkCurrentStatus, 5000);

  // 폼 제출 후 상태 자동 갱신
  $("#shutdown-form").on("submit", function (e) {
    e.preventDefault(); // 기본 제출 막기
    const form = $(this);
    $.post(form.attr("action"), form.serialize())
      .done(function (response) {
        console.log("Shutdown response:", response);
        if (response.status === "success") {
          alert(response.message); // 성공 메시지 표시
        } else if (response.status === "info") {
          alert(response.message); // 정보 메시지 표시
        }
        setTimeout(function () {
          window.location.reload(); // 페이지 새로고침
        }, 1000); // 1초 뒤 새로고침
      })
      .fail(function (err) {
        alert("종료 실패: " + err.responseJSON.message); // 실패 메시지 표시
      });
  });
</script>
{% endblock %}

apps/cam/templates/cam/live.html
{% extends "cam/base.html" %} {% block title %}Live{% endblock %}


  {% block content %}
  <div class="cover-container d-flex w-100 p-3 mx-auto flex-column">
    {% include "cam/header.html" %}

    <main>
      <div class="row">
        {% for cam in cams %}
        <div class="col-md-6 md-4">
          <div class="card m-1">
            <div class="card-body">
              <div class="card-header d-flex flex-row mb-3 justify-content-between fw-bold fs-5">{{ cam.cam_name }}
                <div>
                  <a href="{{url_for("cam.cam_status")}}" class = "link-danger link-offset-2 link-underline link-underline-opacity-0 fs-6">
                    {% if cam.is_recording %}
                    <svg class = "mb-1" viewBox="0 0 14 14"width="14" height="14"  xmlns="http://www.w3.org/2000/svg">
                      <circle cx="7" cy="7" r="6" class="recording-dot" fill="red" />
                    </svg> 녹화 중
                  </a> 
                    {% else %}
                  <a href="{{url_for("cam.cam_status")}}" class = "link-primary link-offset-2 link-underline link-underline-opacity-0 fs-6">
                    <svg class = "mb-1" viewBox="0 0 14 14" width="14" height="14"  xmlns="http://www.w3.org/2000/svg">
                      <circle cx="7" cy="7" r="6" class="waiting-dot" />
                    </svg> 대기 중
                  </a>
                    {% endif %}
                  <div class ="vr"></div>
                    {% if not cam.is_recording %}
                    <a 
                      href="{{ url_for('cam.start_record', camera_id=cam.id) }}"
                      class="link-offset-2 link-underline link-underline-opacity-0 text-primary-emphasis fw-bold fs-6"
                    >
                    <svg class = "mb-1" viewBox="0 0 384 512" width="15px" height ="15px" xmlns="http://www.w3.org/2000/svg">
                    <path d="M73 39c-14.8-9.1-33.4-9.4-48.5-.9S0 62.6 0 80L0 432c0 17.4 9.4 33.4 24.5 41.9s33.7 8.1 48.5-.9L361 297c14.3-8.7 23-24.2 23-41s-8.7-32.2-23-41L73 39z"/></svg>
                      녹화 시작
                    </a>
                    {% else %}
                    <a
                      href="{{ url_for('cam.stop_record_route', camera_id=cam.id) }}"
                      class ="link-offset-2 link-underline link-underline-opacity-0 text-danger fw-bold fs-6"
                    >
                    <svg class = "mb-1" viewBox="0 0 384 512" width="15px" height ="15px" xmlns="http://www.w3.org/2000/svg">
                      <path d="M0 128C0 92.7 28.7 64 64 64H320c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128z"/></svg>  
                    녹화 중지
                    </a>
                    {% endif %}
                </div>
              </div>
                <div id="camera-{{ cam.id }}-stream" class="mt-2">
                  <img src="{{cam.cam_url}}" style="width: 100%" />
                </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </main>

    {% include "cam/footer.html" %} 
    
  </div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js"></script>
<script src="{{url_for ('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}